BUG: Declared static constexpr members need to be defined as constexpr
This patch addresses the following compilation errors with gcc 4.7 and
4.9 with c++11:

itkNumericTraits.cxx:75:38: error: 'constexpr' needed for in-class
initialization of static data member 'const float
itk::NumericTraits<float>::One' of non-integral type [-fpermissive]
 const float NumericTraits< float >:: One;

It has been tested with Apple Clang 7.0.2, GCC 4.9, GCC 5.1 all with
C++11. Without C++11 the code should remain the same.

Change-Id: I58192cebf29885adaf3026444931a387929fedbc