COMP: Use enum in itkStaticConstMacro for old GCC.
GCC older than 4.5 results in linking errors:

Modules/Core/Common/test/CMakeFiles/ITKCommon1TestDriver.dir/itkImageRegionExplicitTest.cxx.o
/Users/lorensen/ProjectsGIT/ITK/Modules/Core/Common/include/itkImageRegion.h:
In instantiation of ‘const unsigned int
itk::ImageRegion<1u>::ImageDimension’:
/Users/lorensen/ProjectsGIT/ITK/Modules/Core/Common/include/itkImageRegion.h:92:
  instantiated from ‘itk::ImageRegion<1u>’
/Users/lorensen/ProjectsGIT/ITK/Modules/Core/Common/test/itkImageRegionExplicitTest.cxx:22:
  instantiated from here
/Users/lorensen/ProjectsGIT/ITK/Modules/Core/Common/include/itkImageRegion.h:92:
error: explicit instantiation of
‘itk::ImageRegion<1u>::ImageDimension’ but no definition available

Explicitly use enum instead of static const for these older GCC compilers since they are known
 to have this limitation. This is for readability and to avoid the overhead of try_compile's.

This is a partial revert of commit a5aeef59.

Also add 'static constexpr' for better compatibility with C++11.

Change-Id: I5e02908112d500aa2aa62d7d1b32631a3da3930e