STYLE: Remove globals, ProcessObject MakeNameFromIndex use std to_string
Removed `ITK_GLOBAL_INDEX_NAMES_NUMBER`, `ITK_GLOBAL_INDEX_NAMES_LENGTH`, and
`globalIndexNames` from the unnamed namespace of itkProcessObject.cxx.
Simplified `ProcessObject::MakeNameFromIndex` by calling `std::to_string`,
instead of using `globalIndexNames`.

Triggered by forum topic "Build ITK 5.0 in Windows", started by Sandro Queiros,
who reported compile errors from VS2015 (before installing VS updates), at
https://discourse.itk.org/t/build-itk-5-0-in-windows/1748 saying:

    itkProcessObject.cxx(54): error C2440: ‘initializing’: cannot convert from ‘const char [3]’ to ‘const char’.