COMP: Fix VNL compilation for wider C++11 support
Initial code added to support C++11 worked with GCC 4.8, but with GCC 4.9
a more strict enforcement of the requirements is enforced.

This was previous reported in https://issues.itk.org/jira/browse/ITK-2976
ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_numeric_traits.h:387:27: error: ‘constexpr’ needed for in-class initialization of static data member ‘zero’ of non-integral type

This problem has surfaced previously was partially fixed in tested compilers
with:
   commit d4b0a9dda5423ac2e28cf5d9b66acc068db4b3b9
   Author: Hans Johnson <hans-johnson@uiowa.edu>
   Date:   Sun Dec 18 12:26:25 2011 -0600
   COMP: Be compliant with ANSI standard

A more complete C++11 compliant solution is presented in this patch set.

Change-Id: Id6964e2b2615ed838c3a0c99f9e204c1ea0d24c9