COMP: Add ITKMontage's PhaseCorrelationOptimizer to API ignore list
Meant to address:

> python "M:/Dashboard/ITK/Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py"
...
Traceback (most recent call last):
  File "M:\Dashboard\ITK\Wrapping\Generators\Python\Tests\verifyGetOutputAPIConsistency.py", line 104, in <module>
    tot, w = checkGetOutputConsistency(o, t)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Dashboard\ITK\Wrapping\Generators\Python\Tests\verifyGetOutputAPIConsistency.py", line 83, in checkGetOutputConsistency
    i.GetOutput()
TypeError: itkPhaseCorrelationOptimizerF2.GetOutput() missing 1 required positional argument: 'index'
itkTestDriver: Process exited with return value: 1