BUG: ITKCommon publically depends on ITKDoubleConversion.
The itkNumberToString.h header in ITKCommon #include's the double-conversion.h
header from the ITKDoubleConversion module. Elevate the dependency
specification from a private dependency to a public dependency so dependent
modules can find double-conversion.h.  This was detected by the IOSTL module:

In file included from /home/matt/src/ITK/Modules/IO/Mesh/include/itkMeshIOBase.h:35:0,
                 from /home/matt/src/ITKSTLMeshIO/include/itkSTLMeshIO.h:23,
                 from /home/matt/src/ITKSTLMeshIO/src/itkSTLMeshIO.cxx:19:
/home/matt/src/ITK/Modules/Core/Common/include/itkNumberToString.h:21:31: fatal error: double-conversion.h: No such file or directory
 #include "double-conversion.h"

Change-Id: I89d4182b0c948327d00d0a46693e874cf82d5bf8