BUG: Fix variable typo `MultiphaseDenseFiniteDifferenceImageFilter` test
Fix variable spelling mistake in `Review` module
`itk::MultiphaseDenseFiniteDifferenceImageFilter` class test file.

Fixes:
```
/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:115:47:
error: use of undeclared identifier 'flter'; did you mean 'filter'?
  ITK_TEST_SET_GET_VALUE(reinitializeCounter, flter->GetReinitializeCounter());
                                              ^~~~~
                                              filter
```

introduced in commit 669a39c.

Raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8135692