COMP: Fix missing include files
Sample error message:

/Users/svc-dashboard/D/Support/ITK-rwdi/Wrapping/castxml_inputs/itkPyCommand.cxx
/Users/svc-dashboard/D/Support/ITK-rwdi/Wrapping/castxml_inputs/itkPyCommand.cxx:16:10: fatal error: 'itkPyCommand.h' file not found
   16 | #include "itkPyCommand.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.