ENH: Improve coverage for itk::FastMarchingImageFilterBase.
Exercise basic object methods.

Test all Set/Get methods using the TEST_SET_GET_VALUE macro, and all
On/Off methods corresponding to boolean members usign the
TEST_SET_GET_BOOLEAN macro.

Use the TRY_EXPECT_NO_EXCEPTION macro to update the filter and save
tryping the try/catch blocks.

Prefer initialization over assignment in variables.

Use the itkNotUsed macro for test input arguments and hence avoid
casting argc and argv to void to avoid compiler warnings.

Remove printing the input (speed) image.

Remove the calls to the Get* methods corresponding to base class
members (specifically: m_SpeedConstant, m_TargetReachedValue, and
m_NormalizationFactor should be tested for itk::FastMarchingBase in
itkFastMarchingBaseTest.cxx; and m_StoppingValue and GetCollectPoints
should be tested for itk::FastMarchingImageFilter in
itkFastMarchingTest.cxx).

Start comments with capital letters.

Minor style changes (such as white spaces between operators and
arguments, improvement of type names and error messages).

-- COMP: Fix missing typename in templated functions
  ITK/Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx:40:3:
  ITK/Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx:45:3:
  ITK/Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx:50:3:
  ITK/Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx:55:3:
  ITK/Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx:60:3:
   error: missing 'typename' prior to dependent type name 'FastMarchingImageFilterType::OutputSizeType'
    FastMarchingImageFilterType::OutputSizeType outputSize;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- BUG: Fix incorrect superclass naming
Missing itkTypeMacro, and incorrect superclass designations
found with EXERCISE_BASIC_OBJECT_METHODS.

-- STYLE: Create unique local function name
Create a test function name that is distinctly different
from the name of the class being tested.

Document explicitly the intent of the testing function.

This testing function is not instrumented to actually
test the filter (too few inputs provided), but rather
tests the basic getters/setters for the base class.

The actuall testing of the algorithms is performed
in other tests.

Co-authored by: Jon Haitz Legarreta Gorroño <jon.haitz.legarreta@gmail.com>