COMP: Address const char[] conversation warning
Simplified `ProcessObject::MakeNameFromIndex` by calling
`std::to_string`,
instead of using `globalIndexNames`.

Triggered by forum topic "Build ITK 5.0 in Windows", started by Sandro
Queiros,
who reported compile errors from VS2015 (before installing VS
updates), at
https://discourse.itk.org/t/build-itk-5-0-in-windows/1748 saying:

    itkProcessObject.cxx(54): error C2440: ‘initializing’: cannot
    convert from ‘const char [3]’ to ‘const char’.

Co-Author: Niels Dekker <N.Dekker@lumc.nl>