BUG: ITK_COMPILER_SUPPORTS_SSE2_64 incorrectly set for 32-bit x86
If the argument -msse2 is used for 32-bit x86 build, then __SSE2__
is defined. This cause ITK_COMPILER_SUPPORTS_SSE2_64 to be set
for 32-bit x86.
MSVC defines _M_AMD64 and _M_X64 also for ARM64EC!
/usr/local/include/ITK-5.3/itkMathDetail.h:317:10: error: use of undeclared identifier '_mm_cvtsd_si64'
  return _mm_cvtsd_si64(_mm_set_sd(x));
         ^
/usr/local/include/ITK-5.3/itkMathDetail.h:326:10: error: use of undeclared identifier '_mm_cvtss_si64'; did you mean '_mm_cvtss_si32'?
  return _mm_cvtss_si64(_mm_set_ss(x));
         ^
/usr/lib/clang/14.0.5/include/xmmintrin.h:1306:1: note: '_mm_cvtss_si32' declared here
_mm_cvtss_si32(__m128 __a)
^
2 errors generated.