COMP: Fix missing type specialization for `unsigned long long int`
Compilation of wrapping types with
`gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

Ensure all integer types have specialization for Fundamental types
defined in C++11:
https://en.cppreference.com/w/cpp/language/types

In file included from /home/johnsonhj/Dashboard/src/ITK/Modules/IO/MeshBase/include/itkMeshFileReader.h:36:0,
                 from /home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Typedefs/itkMeshFileReaderSwigInterface.h:21,
                 from /home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Modules/ITKIOMeshBase/itkMeshFileReaderPython.cpp:3519:
/home/johnsonhj/Dashboard/src/ITK/Modules/IO/MeshBase/include/itkMeshConvertPixelTraits.h: In instantiation of ‘class itk::MeshConvertPixelTraits<long long unsigned int>’:
/home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Modules/ITKIOMeshBase/itkMeshFileReaderPython.cpp:10672:41:   required from here
/home/johnsonhj/Dashboard/src/ITK/Modules/IO/MeshBase/include/itkMeshConvertPixelTraits.h:49:58: error: ‘long long unsigned int’ is not a class, struct, or union type
   using ComponentType = typename PixelType::ComponentType;