BUG: ITKIOMeta needs a public dependency on ITKMetaIO.
This avoids the link error:

  /usr/bin/x86_64-pc-linux-gnu-ld:
  src/CMakeFiles/itkImageReadRegionOfInterestAroundSeedWrite.dir/itkImageReadRegionOfInterestAroundSeedWrite.cxx.o:
  undefined reference to symbol '_ZNK10MetaObject17ObjectSubTypeNameEv'
  /home/matt/bin/ITK-Clang-MinSizeRel/lib/libITKMetaIO-4.9.so.1: error adding
  symbols: DSO missing from command line

with the LesionSizingToolkit module.

Change-Id: Ied2f5ea3ba9a17986dbd35dce916156795c9d752