COMP: Add missing `#include <iostream>` to Deprecated module test
Fixed a Visual C++ 2019 error, saying:

> Deprecated\test\itkSimpleFastMutexLockTest.cxx(48,12): error C2039: 'cout': is not a member of 'std'