COMP: fix type conversion error
d:\a\1\s\include\itkTileMergeImageFilter.hxx(359): error C2440: 'initializing': cannot convert from 'unsigned __int64' to 'unsigned long &'