COMP: Fix BuildInformation GetValue, GetDescription `key` parameter type
The original `key` parameter type `(const MapKeyType &&)` unnecessarily
prevented passing an l-value string to these two member functions. An
attempt to pass an l-value string to one of these member functions would
cause compile errors, like:

> error C2664: cannot convert argument 1 from '_Ty1' to 'const MapKeyType &&'

> error: rvalue reference to type 'const basic_string' cannot bind to lvalue of type 'const basic_string'

> error: cannot bind rvalue reference of type 'const MapKeyType&&' to lvalue of type 'const std::basic_string'

Fixed by making the `key` parameter type an l-value reference instead:
`(const MapKeyType &)`.