BUG: Remove extern "C" call to include <cstring>
In a previous commit [1], includes of C libraries were replaced with includes
of their equivalent C++ libraries. <cstring> is a C++ library, so it should
be included in C++ code, not in C code. Including it in extern "C" code leads to
the following error on Clang 3.8 on Linux:

In file included from /home/fbudin/Devel/ITK/Modules/Core/Common/test/itkHashTableTest.cxx:33:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/cstring:100:3: error: conflicting types for 'memchr'
  memchr(void* __s, int __c, size_t __n)
  ^
/usr/include/string.h:92:14: note: previous declaration is here
extern void *memchr (const void *__s, int __c, size_t __n)
             ^
In file included from /home/fbudin/Devel/ITK/Modules/Core/Common/test/itkHashTableTest.cxx:33:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/cstring:104:3: error: conflicting types for 'strchr'
  strchr(char* __s, int __n)
  ^
/usr/include/string.h:231:14: note: previous declaration is here
extern char *strchr (const char *__s, int __c)
             ^
In file included from /home/fbudin/Devel/ITK/Modules/Core/Common/test/itkHashTableTest.cxx:33:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/cstring:108:3: error: conflicting types for 'strpbrk'
  strpbrk(char* __s1, const char* __s2)
  ^
/usr/include/string.h:310:14: note: previous declaration is here
extern char *strpbrk (const char *__s, const char *__accept)
             ^
In file included from /home/fbudin/Devel/ITK/Modules/Core/Common/test/itkHashTableTest.cxx:33:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/cstring:112:3: error: conflicting types for 'strrchr'
  strrchr(char* __s, int __n)
  ^
/usr/include/string.h:258:14: note: previous declaration is here
extern char *strrchr (const char *__s, int __c)
             ^
In file included from /home/fbudin/Devel/ITK/Modules/Core/Common/test/itkHashTableTest.cxx:33:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.1/../../../../include/c++/5.4.1/cstring:116:3: error: conflicting types for 'strstr'
  strstr(char* __s1, const char* __s2)
  ^
/usr/include/string.h:337:14: note: previous declaration is here
extern char *strstr (const char *__haystack, const char *__needle)
             ^
5 errors generated.

[1] https://github.com/InsightSoftwareConsortium/ITK/commit/eda50f9#diff-e4e6ace

Change-Id: I0ed24d503730c9a68e0a86853bb50fb6ae05dd19