COMP: Add missing ITKIOImageBase dependency for ITKTransformMINC.
This addresses:

In file included from /home/matt/src/ITK/Modules/IO/TransformMINC/include/itkMINCTransformIO.hxx:27:0,
                 from /home/matt/src/ITK/Modules/IO/TransformMINC/include/itkMINCTransformIO.h:100,
                 from /home/matt/src/ITK/Modules/IO/TransformMINC/src/itkMINCTransformIOFactory.cxx:21:
/home/matt/src/ITK/Modules/IO/MINC/include/itkMINCImageIO.h:30:28: fatal error: itkImageIOBase.h: No such file or directory
 #include "itkImageIOBase.h"

Change-Id: Idb99a44e839dd5abd0f77e32530498e1d56ddef3