COMP: Fix ITKDeprecated module test in TestExternal build
Avoid referencing ITKDeprecated_SOURCE_DIR because the module source
directory is not processed during the TestExternal build.  Instead refer
to the test source directory with CMAKE_CURRENT_SOURCE_DIR.  This fixes
the compilation error:

  .../Testing/TestExternal/Modules/Compatibility/Deprecated/test/DeprecatedIOTestDriver.cxx:6:55:
  error: itkTestDriverIncludeDeprecatedIOFactories.h: No such file or directory

by correctly referencing the include directory containing the header.