COMP: fix type conversion error in GPUPDEDeformableRegistrationFilter
C:\Dev\ITK-git\Modules\Registration\GPUPDEDeformable\include\itkGPUPDEDeformableRegistrationFilter.hxx(336,1): error C2440: 'initializing': cannot convert from 'size_t' to 'unsigned long &'