COMP: Add missing brackets to RelabelComponentsImageFilterGTest
To address the dashboard warning:

   Standard Error

[CTest: warning matched] /Users/builder/externalModules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx:141:54: warning: suggest braces around initialization of subobject [-Wmissing-braces]
  image->SetRegions(typename ImageType::RegionType({ 512, 512, 512 }));
                                                     ^~~~~~~~~~~~~
                                                     {            }
[CTest: warning suppressed] 1 warning generated.

Also, disambiguate construction re:

  Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx:141:21: error: call to constructor of 'typename ImageType::RegionType' (aka 'ImageRegion<3U>') is ambiguous