COMP: Invalid conversion detected by clang c++11
Removed private member function that is never used
by the class.

istream::operator>> returns a reference to an istream
that is not convertable to a boolean.

istream& operator>> (long& val);

This test case confirms that this is really invalid code:

cat test_conversion.cpp
\#include <iostream>
\#include <sstream>
\#include <string>
int main(int argc, char * argv[])
{
  typedef long int DataObjectPointerArraySizeType;
  DataObjectPointerArraySizeType idx;
  std::string idxStr = "7";
  return (std::istringstream(idxStr) >> idx);
}

clang++ -std=c++11 test_conversion.cpp

test_conversion.cpp:9:10: error: no viable conversion from 'std::__1::basic_istream<char>' to 'int'
  return (std::istringstream(idxStr) >> idx);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I1979f063af664c7782ddfc73d539973631e13d9c