COMP: fix link errors coming from undefined static constexpr member
Modules/Core/Common/include/itkSymmetricEigenAnalysis.h:869: error: undefined reference to 'itk::SymmetricEigenAnalysisFixedDimension<3u, itk::Matrix<double, 3u, 3u>, itk::FixedArray<double, 3u>, itk::Matrix<double, 3u, 3u> >::m_Dimension'

This looks like the same problem as in this StackOverflow question:
https://stackoverflow.com/questions/40690260/undefined-reference-error-for-static-constexpr-member

The solution is to avoid introducing static constexpr member
and using the template parameter directly.