COMP: Missing ProgressReporter header
This patch addresses the following compilation error seen on some
systems with WrapITK enabled:

/.../ITK/Modules/Filtering/LabelMap/include/itkChangeRegionLabelMapFilter.hxx:85:5:
error: 'ProgressReporter' was not declared in this scope

Change-Id: Iefd03cd6cdfdbd55c225410dd6d9d3ced3c30a9e