COMP: Address empty _FILE_OFFSET_BITS in tif_config.h with MinGW64
_FILE_OFFSET_BITS is expected to have a value of 32 or 64 or be
undefined.

Addresses:

FAILED: Modules/ThirdParty/TIFF/src/itktiff/CMakeFiles/itktiff.dir/tif_packbits.c.obj
C:\msys64\mingw64\bin\cc.exe -DJPEG_SUPPORT -DTIF_PLATFORM_CONSOLE -DZIP_SUPPORT -D_HPUX_SOURCE -IModules/ThirdParty/TIFF/src/itktiff -IC:/ITK/Modules/ThirdParty/TIFF/src/itktiff -IModules/ThirdParty/JPEG/src -IC:/ITK/Modules/ThirdParty/JPEG/src -IModules/ThirdParty/KWIML/src -IC:/ITK/Modules/ThirdParty/KWIML/src -IModules/ThirdParty/ZLIB/src -IC:/ITK/Modules/ThirdParty/ZLIB/src -IModules/ThirdParty/TIFF/src -IC:/ITK/Modules/ThirdParty/TIFF/src -Wno-uninitialized -Wno-unused-parameter -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow  -mthreads -w -fno-strict-aliasing -O3 -DNDEBUG -MD -MT Modules/ThirdParty/TIFF/src/itktiff/CMakeFiles/itktiff.dir/tif_packbits.c.obj -MF Modules\ThirdParty\TIFF\src\itktiff\CMakeFiles\itktiff.dir\tif_packbits.c.obj.d -o Modules/ThirdParty/TIFF/src/itktiff/CMakeFiles/itktiff.dir/tif_packbits.c.obj   -c C:/ITK/Modules/ThirdParty/TIFF/src/itktiff/tif_packbits.c
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/io.h:178:0,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/fcntl.h:8,
                 from C:/ITK/Modules/ThirdParty/TIFF/src/itktiff/tiffiop.h:36,
                 from C:/ITK/Modules/ThirdParty/TIFF/src/itktiff/tif_packbits.c:27:
C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw_off_t.h:23:55: error: operator '==' has no left operand
 #if (defined(_FILE_OFFSET_BITS) && (_FILE_OFFSET_BITS == 64))
                                                       ^~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/fcntl.h:8:0,
                 from C:/ITK/Modules/ThirdParty/TIFF/src/itktiff/tiffiop.h:36,
                 from C:/ITK/Modules/ThirdParty/TIFF/src/itktiff/tif_packbits.c:27:
C:/msys64/mingw64/x86_64-w64-mingw32/include/io.h:349:55: error: operator '==' has no left operand
 #if (defined(_FILE_OFFSET_BITS) && (_FILE_OFFSET_BITS == 64))

Change-Id: Ic7af992d849f5db33087d5a2e45646a5d6e84072