COMP: Missing return error after exception
VS 2010 complains when a function that throws an exception does not
return a value. Some other VS compilers may warn rather than error.

Typical error:
error C4716: 'itk::Transform<double,3,3>::TransformVector' : must
return a value

Change-Id: Iddff1d5899dcb3d35587e96ee10b3446981cd462