BUG: Initialize C++ standard for remote modules
We now default to C++14, which is not the default standard on most compilers. Addresses:

  Modules/Core/Common/include/itkMacro.h:192:6: error: "Apple LLVM < 5.1 (clang < 3.4) is not supported under ITKv5.3"

When building remote modules externally, which is triggered by too low of a C++ standard.