COMP: test fails to compile when legacy support is removed
itkMetaProgrammingLibraryTest is testing itkStaticAssert,
which has been recently deprecated.
When ITK_LEGACY_REMOVE is turned on, it caused compiler errors
of the following style:

Modules/Core/Common/test/itkMetaProgrammingLibraryTest.cxx line 33 (https://open.cdash.org/viewBuildError.php?type=0&amp;buildid=7345514
M:\Dashboard\ITK\Modules\Core\Common\test\itkMetaProgrammingLibraryTest.cxx(33): error C2065: 'Use': undeclared identifier [M:\Dashboard\ITK-build\Modules\Core\Common\test\ITKCommon2TestDriver.vcxproj]