COMP: Add missing HDF5 include for MINC.
This addresses:

  In file included from
  /Users/builder/external/ITK/Modules/IO/MINC/src/itkMINCImageIOFactory.cxx:19:
  In file included from
  /Users/builder/external/ITK/Modules/IO/MINC/include/itkMINCImageIO.h:34:
  In file included from
  /Users/builder/external/ITK-clang-dbg-x86_64-static/Modules/ThirdParty/MINC/src/itk_minc2.h:43:
  In file included from
  /Users/builder/external/ITK-clang-dbg-x86_64-static/Modules/ThirdParty/MINC/ITKMINC2_ExternalProject/libsrc2/minc2.h:10:
  /Users/builder/external/ITK-clang-dbg-x86_64-static/Modules/ThirdParty/MINC/ITKMINC2_ExternalProject/libsrc2/minc2_structs.h:5:10:
  fatal error: 'H5public.h' file not found
  #include "H5public.h"
           ^
           1 error generated.

Change-Id: I699f7e355f80d6cba7d3fe44ab14f451b1b947ab