COMP: Correct TEMPLATE_EXPLICIT definition in Path module
Address compilation with VS9 2008 with static library. The declaration
of the explicit template with extern causes the following compilation
error:
itkParametricPath.cxx(34) : error C2960: 'itk::ParametricPath' :
inconsistent explicit instantiations, a previous explicit
instantiation specified 'extern template'

Change-Id: If85a4fb5f78f6a11e8be858ce541329d859dd4a1