BUG: Address missing shared_ptr for VS9
This patch addresses the following compilation error:

vxl\vcl\vcl_compiler.h(940): fatal error C1189: #error :  "Missing
definition for SHARED_PTR"

Older Visual Studio have tr1 include not in a tr1 directory but still
in the tr1 namespace, this patch add support for this configuration.

This is a backport of vxl/vxl@7e9e129811cb20f7.

Change-Id: Ic233c6ffc734b1c600240bc593bcd59dd5a08866