BUG: Fix a sun build missing uintmax_t
This is an atempt to fix the following compilation error:

In file included from
/home/papha/glehmann/src/tests/ITK-gcc64/Modules/IO/RAW/test/ITKIORAWHeaderTest1.cxx:23:
/export/home/glehmann/src/tests/ITK/Modules/IO/RAW/include/itkRawImageIO.hxx:
In member function `itk::SizeValueType itk::RawImageIO<TPixel,
VImageDimension>::GetHeaderSize()':
/export/home/glehmann/src/tests/ITK/Modules/IO/RAW/include/itkRawImageIO.hxx:86:
error: no class template named `intmax_t' in `itk'
/export/home/glehmann/src/tests/ITK/Modules/IO/RAW/include/itkRawImageIO.hxx:87:
error: no class template named `intmax_t' in `itk'

The Sun compilers have previously been fickel about the order of headers.

Change-Id: Id9af2dfd3846d3ba97a13211d578881606a57c8e