COMP: Move itkMatrixCoefficients wrapping to Filtering module
itkMatrixCoefficients has been moved to /Filtering/QuadEdgeMeshFiltering/
When building+wrapping ITK with Core alone, you would get the following error:

[ 86%] Generating itkMatrixCoefficients.xml
cd /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKQuadEdgeMesh && ../../Generators/GccXML/gccxml/bin/gccxml -fxml-start=_cable_ -fxml=/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKQuadEdgeMesh/itkMatrixCoefficients.xml --gccxml-gcc-options /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKQuadEdgeMesh/gcc_xml.inc -DCABLE_CONFIGURATION -DITK_MANUAL_INSTANTIATION /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKQuadEdgeMesh/itkMatrixCoefficients.cxx
/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKQuadEdgeMesh/itkMatrixCoefficients.cxx:18:52: error: itkQuadEdgeMeshParamMatrixCoefficients.h: No such file or directory

Change-Id: I417f79c571442e00419baa2f00047e52acb2a5af