COMP: No longer test `is_trivially_copyable` in itkMatrixGTest on GCC 4
Worked around:

> ITK/Modules/Core/Common/test/itkMatrixGTest.cxx:44:15: error:
> 'is_trivially_copyable' is not a member of 'std'

From CDash (https://open.cdash.org/viewBuildError.php?buildid=7131131):
> Site: AWS-BATCH-88ede920-9899-42aa-8b05-b6d829ac45d3
> Build Name: CentOS Coverage
> Build Time: 2021-03-30 04:52:57

Reported by Matt McCormick at pull request
"ENH: Make itk::Matrix trivially copyable, following Rule of Zero"
https://github.com/InsightSoftwareConsortium/ITK/pull/2449