COMP: Fix `Regitration::FEM` module `PrintSelf` compiler errors
Fix miscellaneous compiler errors in `Registration::FEM` module classes'
`PrintSelf` methods.

Fixes:
```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2440:
'static_cast':
cannot convert from 'const itk::fem::Solution::ConstPointer' to 'const itk::LightObject *'
```

```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2039:
'Print': is not a member of 'itk::fem::Solution'
```

and
```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,22):
error C2275:
'itk::fem::Material': expected an expression instead of a type
```

```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,3):
error C3861:
'itkPrintSelfObject': identifier not found
```

and
```
ITK\Modules\Registration\FEM\include\itkFEMRegistrationFilter.hxx(1471,9):
error C2440:
'static_cast': cannot convert from 'const unsigned int' to 'itk::Size<3>'
```

```
ITK\Modules\Registration\FEM\include\itkFEMRegistrationFilter.hxx(1529,16):
error C2679:
binary '<<': no operator found which takes a right-hand operand of type
'const itk::fem::FEMRegistrationFilter<InputImageType,InputImageType,FEMObjectType>::LandmarkArrayType'
(or there is no acceptable conversion)
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8462352

Inadvertently introduced in c47ed1c1b3e26051de655f7ad03e975fae93b73b.