COMP: Remove itkTypeMacro from BioCellHelper.
Since this class does not inherit from itk::LightObject, it cannot use
itkTypeMacro.  This addresses the build errors that occur with C++11:

/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:45:3: error: 'GetNameOfClass' marked 'override' but does not override any member functions
  itkTypeMacro( BioCellHelper, itk::bio::Cell );
  ^
/home/matt/src/ITK2/Modules/Core/Common/include/itkMacro.h:315:23: note: expanded from macro 'itkTypeMacro'
  virtual const char *GetNameOfClass() const ITK_OVERRIDE \
                      ^
/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:187:3: note: in instantiation of template class 'BioCellHelper<2>' requested here
  BioCellHelper<dimension2D>::VectorType forceVector2D;
  ^
/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:45:3: error: 'GetNameOfClass' marked 'override' but does not override any member functions
  itkTypeMacro( BioCellHelper, itk::bio::Cell );
  ^
/home/matt/src/ITK2/Modules/Core/Common/include/itkMacro.h:315:23: note: expanded from macro 'itkTypeMacro'
  virtual const char *GetNameOfClass() const ITK_OVERRIDE \
                      ^
/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:206:3: note: in instantiation of template class 'BioCellHelper<3>' requested here
  BioCellHelper<dimension3D>::VectorType forceVector3D;
  ^
/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:45:3: error: 'GetNameOfClass' marked 'override' but does not override any member functions
  itkTypeMacro( BioCellHelper, itk::bio::Cell );
  ^
/home/matt/src/ITK2/Modules/Core/Common/include/itkMacro.h:315:23: note: expanded from macro 'itkTypeMacro'
  virtual const char *GetNameOfClass() const ITK_OVERRIDE \
                      ^
/home/matt/src/ITK2/Modules/Segmentation/BioCell/test/itkBioCellTest.cxx:226:3: note: in instantiation of template class 'BioCellHelper<4>' requested here
  BioCellHelper<dimension4D>::VectorType forceVector4D;
  ^
3 errors generated.

Change-Id: I32256fae255ddfd3dc5f7ca652cb99910554f380