COMP: Workaround VS2017 error C2653/C2886 using-declaration compiler bug
Partially reverted pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2567
commit 4f309803b9b3c0268679d658e22d2f751f9c7b6c "STYLE: Avoid repeating parent aliases"
because of Visual Studio 2017 compile errors reported by Dženan Zukić at
https://github.com/InsightSoftwareConsortium/ITK/pull/2759 "COMP: making it compile on VS2017"

Worked around the following VS2017 compile errors:

> error C2653: '...': is not a class or namespace name
> error C2886: '...': symbol cannot be used in a member using-declaration

The compiler bug that caused these errors is reported here:
"Compile error when using "using declaration" referencing a base class type that refers to itself"
EssentiaX - Reported March 12, 2019 [Fixed in version 16.2]
https://developercommunity.visualstudio.com/t/486683