COMP: Fix error: constexpr variable 'ImageIOFactoryRegisterRegisterList'
Replaced `constexpr` by `const` in itk*IOFactoryRegisterManager.h.in
files, in order to work around ITK.Windows.Python CI errors at
Azure.fv-az77-327, build Windows_NT-Build2622-master-Python (Visual
Studio 2019 v16.11.4, MSVC 19.29.30136.0) at
https://open.cdash.org/viewBuildError.php?buildid=7515599 saying:

> D:/a/1/s-build/Wrapping/ITKFactoryRegistration\itkImageIOFactoryRegisterManager.h:49:18: error: constexpr variable 'ImageIOFactoryRegisterRegisterList' must be initialized by a constant expression

These errors occurred after pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2811
"Fix various Clang-Tidy warnings from the three
itk*IOFactoryRegisterManager.h.in files" commit f56cc7ef17d27804932e61e4b4aa764858047013
"COMP: Add "const" to `IOFactoryRegisterManager` implementations"