COMP: Type ambiguity when argument is const
Changing variable to const caused windows builds
to fail.

error C2666: 'MetaImage::SequenceID': 2 overloads have similar conversions

Filtering\ImageFeature\include\itkZeroCrossingImageFilter.hxx(64): error C2668: 'itk::ImageRegion<3>::PadByRadius': ambiguous call to overloaded function
Core\Common\include\itkImageRegion.h(333): note: could be 'void itk::ImageRegion<3>::PadByRadius(const __int64 [])'
Core\Common\include\itkImageRegion.h(330): note: or       'void itk::ImageRegion<3>::PadByRadius(__int64)'
Filtering\ImageFeature\include\itkZeroCrossingImageFilter.hxx(64): note: while trying to match the argument list '(const itk::SizeValueType)'
Filtering\ImageFeature\include\itkZeroCrossingImageFilter.hxx(43): note: while compiling class template member function 'void itk::ZeroCrossingImageFilter<itk::Image<float,3>,itk::Image<float,3>>::GenerateInputRequestedRegion(void)'
Segmentation\LevelSets\include\itkSparseFieldLevelSetImageFilter.hxx(470): note: see reference to class template instantiation 'itk::ZeroCrossingImageFilter<itk::Image<float,3>,itk::Image<float,3>>' being compiled
Segmentation\LevelSets\include\itkSparseFieldLevelSetImageFilter.hxx(454): note: while compiling class template member function 'void itk::SparseFieldLevelSetImageFilter<TInputImage,TOutputImage>::CopyInputToOutput(void)'