DOC: Fix missing \ingroup ITKIODCMTK
Modules/IO/DCMTK/include/itkDCMTKImageIO.h:31: error: "\ingroup non" not set in class DCMTKImageIOEnums.
Modules/IO/DCMTK/include/itkDCMTKImageIO.h:38: error: "\ingroup ITKIODCMTK" not set in class LogLevel.

1/1 Test #850: ITKIODCMTKInDoxygenGroup .........***Failed    0.04 sec