BUG: Bounds type in GenerateData() needs to be of type PadFilterType::SizeType
Using an array of type `long` leads to compilations errors on Windows:

error C2664: 'void itk::PadImageFilter::SetPadLowerBound(const unsigned
	__int64 [])': cannot convert argument 1 from 'unsigned long [2]'
	to 'const itk::Size<2>'