COMP: WindowedSincInterpolate OffsetTable return type [VS2017 fix]
Fixes compile error on Visual Studio 2017. The full error message is:

M:\Dashboard\ITK\Modules\Core\ImageFunction\include\itkWindowedSincInterpolateImageFunction.h(346): error C2397: conversion from 'TReturnType' to 'const unsigned int' requires a narrowing conversion [M:\Dashboard\ITK-build\Modules\Core\Common\test\ITKCommon1TestDriver.vcxproj]

M:\Dashboard\ITK\Modules\Core\Common\test\itkPhasedArray3DSpecialCoordinatesImageTest.cxx(96): note: see reference to class template instantiation 'itk::WindowedSincInterpolateImageFunction<Image,3,itk::Function::HammingWindowFunction<3,double,double>,itk::ZeroFluxNeumannBoundaryCondition<TInputImage,TInputImage>,double>' being compiled