COMP: Remove in class init of SmartPointer of forward declaration
GCC 7.4.1 raised the following errors on Linux:
Modules/Core/Common/include/itkSmartPointer.h:214:18: error: invalid use
of incomplete type ‘using ObjectType = class itk::MultiThreaderBase {aka
class itk::MultiThreaderBase}’

This is a compiler bug (as discussed in
https://github.com/InsightSoftwareConsortium/ITK/pull/3877#issuecomment-1398456306)
and the same issue has been fixed for unique_ptr by
719c3ce349a0529f908b56817d02a33e7fb8ccde.