COMP: Use trailing return type instead of `typename` + dependent type
Modernized template member function definitions in "itk*.hxx" files by
using trailing return types, specifically for return types that are
themselves specified in terms of a member type, dependent on the
specific class template.

These changes appeared to serve as a workaround to VS2017 compile errors
(apparently caused by a compiler bug) saying:

> error C2244: unable to match function definition to an existing declaration

By Notepad++ v8.1.4, Find in Files:

    Find what: ^typename (\w+<.+>::)(.+)\r\n\1(.+)\r\n{\r\n
    Replace with: auto\r\n$1$3 -> $2\r\n{\r\n
    Filter: itk*.hxx
    [v] Match case
    (*) Regular expression

Manually fixed `PatchBasedDenoisingBaseImageFilter::GetPatchLengthInVoxels()`.
Manually added `typename` to trailing return types, where necessary.