COMP: Add missing H5T_patch_vlen_file declaration
Addresses:

/work/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Dio.c:424:5: error: implicit declaration of function 'H5T_patch_vlen_file' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    H5T_patch_vlen_file(dataset->shared->type, dataset->oloc.file);
    ^
/work/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Dio.c:424:5: note: did you mean 'H5T_patch_file'?
/work/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Tprivate.h:138:15: note: 'H5T_patch_file' declared here
H5_DLL herr_t H5T_patch_file(H5T_t *dt, H5F_t *f);

Change-Id: Iea00848dc898a2d56a022ad6d5e293b4c0ea49b1