COMP: GCC_XML compilation error with type_traits
This patch addresses a WrapITK compilation error with gcc_xml like the
following:

In file included from
/home/kevin/kitware/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:25,
                 from
                 /home/kevin/kitware/ITK/Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h:24,
                 from
                 /home/kevin/kitware/ITK/Modules/Filtering/ImageFilterBase/include/itkBoxImageFilter.h:23,
                 from
                 /home/kevin/kitware/ITK/Modules/Filtering/ImageStatistics/include/itkAdaptiveHistogramEqualizationImageFilter.h:22,
                 from
                 /home/kevin/kitware/ITK_Build/Wrapping/Modules/ITKImageStatistics/itkAdaptiveHistogramEqualizationImageFilter.cxx:22:
/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tr1/type_traits:208:
error: a function call cannot appear in a constant-expression
/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/tr1/type_traits:208:
error: template argument 2 is invalid

There is no logical reason why including ImageAlgorithm in both the h
and hxx files should have caused this error.

Change-Id: Idb12acc6c9cda0c552fb57b60141393bdfe972e0