COMP: use WRAP_ITK_SCALAR instead of WRAP_ITK_REAL in mesh filters
It would cause runtime errors such as:

itk.meshwrite(mesh, file_path)
   ...
itk.support.extras.TemplateTypeError: itk.MeshFileWriter is not wrapped for input type `itk.Mesh[itk.UC,3]`.
To limit the size of the package, only a limited number of
types are available in ITK Python.
...
Supported input types:
itk.Mesh[itk.F,2]
itk.Mesh[itk.D,2]
itk.Mesh[itk.F,3]
itk.Mesh[itk.D,3]