COMP: Replace ITK_TEMPLATE_TXX with ITK_MANUAL_INSTANTIATION
Addresses:

  ITK/Modules/Core/Common/include/itkMacro.h:500:27: error: token ""error
  ITK_TEMPLATE_TXX is no longer a supported identifier, you should replace
  with ITK_MANUAL_INSTANTIATION as a replacement"" is not valid in
  preprocessor expressions