BUG: Fix failure of ITK_EIGEN macro expansion
DOC: Add how-to re-use internal Eigen3 in a external project
ENH: Remove EIGEN_MPL2_ONLY compile definition when using system Eigen3

When including the macro ITK_EIGEN twice in a header, the expansion was
wrong:

```cpp
ITK_EIGEN(Eigenvalues)
ITK_EIGEN(Eigenvalues)
```

The first macro would expand correctly to:

```cpp
// #include "itkeigen/Eigen/Eigenvalues"
```

but the second, will change `Eigen` for `itkeigen`, generating:

```cpp
fatal error: itkeigen/itkeigen/Eigenvalues: No such file or directory
```

Minimal working example for testing:

`CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.10.2)

project(tester)

find_package(ITK REQUIRED)
include(${ITK_USE_FILE})

add_executable(tester tester.cpp )
target_link_libraries(tester ${ITK_LIBRARIES})
// Example:
// Use this approach to re-use the internal Eigen3 itk in a third-party
// No need of using the macro ITK_EIGEN then.
// set(_internal_cmake_eigen3)
// list(GET ITKEigen3_INCLUDE_DIRS 0 _internal_cmake_eigen3)
// set(Eigen3_DIR "${_internal_cmake_eigen3}/itkeigen")
// find_package(Eigen3 REQUIRED CONFIG)
```

`tester.cpp`

```cpp
// #include "itk_eigen.h"
// #include ITK_EIGEN(Eigenvalues)
// #include ITK_EIGEN(Eigenvalues)
// #include ITK_EIGEN(SparseCholesky) //uncommenting causes the error "The SparseCholesky module has nothing to offer in MPL2 only mode"
int main()
{
  return 0;
}
```