COMP: Restore `PrintSelf` in itkGPUPDEDeformableRegistrationFilter.h
Restore the `PrintSelf` method override in
`itkGPUPDEDeformableRegistrationFilter.h`.

Fixes:
```
GPUPDEDeformableRegistrationFilterKernel.cxx
Modules\Registration\GPUPDEDeformable\include\itkGPUPDEDeformableRegistrationFilter.hxx(78,104):
error C2995:
'void itk::GPUDenseFiniteDifferenceImageFilter<TInputImage,TOutputImage,TParentImageFilter>::PrintSelf(std::ostream &,itk::Indent) const':
function template has already been defined
Modules\Core\GPUFiniteDifference\include\itkGPUDenseFiniteDifferenceImageFilter.h(105):
message : see declaration of
'itk::GPUDenseFiniteDifferenceImageFilter<TInputImage,TOutputImage,TParentImageFilter>::PrintSelf'
Modules\Registration\GPUPDEDeformable\include\itkGPUPDEDeformableRegistrationFilter.hxx(118,1):
error C2977:
'itk::GPUDenseFiniteDifferenceImageFilter<TInputImage,TOutputImage,TParentImageFilter>':
too many template arguments
```

Removed inadvertently in commit c44f9c1b39e627c5ef7fabec252232a92d570565.

Fix the associated compilation errors in the `PrintSelf` method
implementation.