COMP: Replace "CoordRep" with "Coordinate" in Examples
Addressed a compile error at Mac12.x-AppleClang-dbg-Universal saying:

> MeshSpatialObject.cxx:66:13: error: no type named 'CoordRepType' in
> 'itk::Mesh<float, 3, itk::DefaultDynamicMeshTraits<float, 3>>'

Reported by Jon Haitz Legarreta Gorroño.

- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4997
commit 15d189f513ac63e3cafc77a58b39c8862ce6e844
"STYLE: Replace CoordRepType with CoordinateType in ITK implementation"