COMP: Fix declaration and syntax errors in Review class `PrintSelf`
Fix declaration and syntax errors in Review module class `PrintSelf`
method.

Fixes:
```
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx:1414:30:
error: 'm_FunctionCount' was not declared in this scope; did you mean 'SetFunctionCount'?

 1414 |   for (IdCellType i = 0; i < m_FunctionCount; ++i)
      |                              ^~~~~~~~~~~~~~~
      |                              SetFunctionCount
```

and
```
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx:1443:52:
error: expected '>' before '(' token

 1443 |       typename NumericTraits<IdCellType>::PrintType(sparsePtr->m_Index) << std::endl;
      |                                                    ^
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8456002

Inadvertently introduced in c47ed1c1b3e26051de655f7ad03e975fae93b73b.