COMP: Add a missing head file at itkNumericTraitsStdVector.h
- Add the header file of "itkMath.h" at the itkNumericTraitsStdVector.h
  to fix the following error:

  error: 'itk::Math' has not been declared

Change-Id: I909f983b1108c50121f4e8c6aa2c1d982a89d8c8