COMP: Type mis-match for comparison operator
In the specialized operator= the types will not
match, so the test for being the same pointer
is not valid.

itkDiffusionTensor3D.h:124:13: error: comparison of distinct pointer types
   ('itk::DiffusionTensor3D<double> *' and 'const DiffusionTensor3D<float> *')
   (this != &pa)
    ~~~~ ^  ~~~

Change-Id: I6fabab1d546226880cbc5648a698b60b2e71fe9e