ENH: Workaround MSVC preprocessor name conflict
STRICT is a preprocessor defined value.

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2059\?view\=vs-2019

C2059 is raised when a preprocessor symbol name is re-used as an
identifier. In the following example, the compiler sees DIGITS.ONE as
the number 1, which is not valid as an enum element name:

```cxx
\#define ONE 1  // <-- THIS WILL CAUSE AN ERROR
enum class DIGITS {
	ZERO,
	ONE // error C2059
};
```