DOC: Fixed missing doxygen ingroup
/scratch/johnsonhj/src/Dashboards/src/ITK/Modules/Compatibility/V3Compatibility/include/itkOtsuThresholdImageCalculator.h:28:
error: "\ingroup ITKV3Compatibility" not set in class
OtsuThresholdImageCalculator.

Change-Id: I85313bbd6552dee1b6396e06d044228628be81c6