COMP: Clang compiler regression
error: label at end of compound statement: expected statement

This error occurs with:
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0

The solution is to add an explicit 'break' statement,
or remove the final default clause.

Change-Id: I11ed0cdd6d8005ab8a1f42091943166b9d702f3c