BUG: Don't force GDCM_USE_COREFOUNDATION_LIBRARY to OFF
Because this is forced off GDCM/ITK spew logs:

Error: In /Users/builder/official_builds/InsightToolkit-4.13.0/Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmSystem.cxx, line 461, function static const char *gdcm::System::GetCurrentProcessFileName()
missing implementation

This forcing to off was added in b388a3bb to workaround some link errors, but I think the proper solution for that would have been to link against the CoreFoundation framework, which is available in all versions of macOS.

I suspect something else has changed in the meantime, because I can't reproduce any such link errors.

Change-Id: I995a996764295b4dc977dd0c0d65c2683026fd6f