COMP: Remove comparison to FixedArray in MatrixOffsetTransformBase GTest
Comparing an `itk::FixedArray` to an `itk::Point` appears to cause C++20
compilation errors, as observed with Visual Studio 2019 ("/std:c++latest"),
reported by QuellaZhang, issue https://github.com/InsightSoftwareConsortium/ITK/issues/2640

> itkMatrixOffsetTransformBaseGTest.i(390249): error C2666: 'itk::FixedArray<double,2>::operator ==': 2 overloads have similar conversions
> itkMatrixOffsetTransformBaseGTest.i(87990): note: could be 'bool itk::FixedArray<double,2>::operator ==(const itk::FixedArray<double,2> &) const'
> itkMatrixOffsetTransformBaseGTest.i(390240): note: or       'bool testing::internal::operator ==(testing::internal::faketype,testing::internal::faketype)'
> itkMatrixOffsetTransformBaseGTest.i(269102): note: or 'bool itk::Point<TParametersValueType,2>::operator ==(const itk::Point<TParametersValueType,2> &) const' [synthesized expression 'y == x']