COMP: Do not use C++11 alignas in itkAlignedTypedef.
According to the standard, alignas cannot be used with typedef's.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3093.html

  An alignment specifier shall not be specified in a declaration of a typedef,
  or a bit-field, or a reference, or a function parameter or return type, or an
  object declared with the register storage-class specifier. [Note: In short,
  the specifier can be used on automatic variables, namespace scope variables,
  and members of class types (as long as they are not bit-fields). In other
  words, it cannot be used in contexts where it would become part of a type and
  therefore would affect name mangling, name lookup or ordering of function
  templates. —end note]

Clang errors with:

  ITK/Modules/Core/Common/include/itkAtomicIntDetail.h:126:3:
  error: 'alignas' attribute only applies to variables, data members and tag
  types
    itkAlignedTypedef( 8, int64_t, Type );
      ^

when passed through castxml with -std=c++11.

Suggested-by: Brad King <brad.king@kitware.com>

Change-Id: I81795cb982c57c07a31521b4895b83cec026aafb