COMP: Add #include "itkNumericTraitsVectorPixel.h", for `MeanVectorType`
Appears necessary for `NumericTraits<MeasurementVectorType>::RealType`,
which is used to define `MeanVectorType`, indirectly.

Addresses Linux Python build errors saying:

> Wrapping/Modules/ITKLevelSets/itkVectorThresholdSegmentationLevelSetImageFilterPython.cpp:
> 3906:44: error: no matching function for call to
> `VectorThresholdSegmentationLevelSetImageFilter<Image<float, 2>, Image<Vector<float, 2>, 2>, float>::SetMean(const double&)`

At https://open.cdash.org/viewBuildError.php?buildid=7780689