BUG: Fix Python tests on Windows with Ninja generator.
When the Ninja generator is used on Windows, there is not a configuration
type in the binary path; we need <build-dir>/bin added to PATH variable
for the tests to run. This addresses the error:

Loading ITKPyBase...done
Loading ITKCommon...Traceback (most recent call last):
  File "C:/Jenkins/workspace/ITKWindowsPython/ITK-src/Wrapping/Generators/Python/Tests/BinaryDilateImageFilter.py", line 36, in <module>
    ImageType = itk.Image[PixelType, Dimension]
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkLazy.py", line 42, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 118, in LoadModule
    module = loader.load(swigModuleName)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\Wrapping\Generators\Python\itkBase.py", line 224, in load
    return imp.load_module(name, fp, pathname, description)
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\lib\ITKCommonPython.py", line 32, in <module>
    _ITKCommonPython = swig_import_helper()
  File "C:\Jenkins\workspace\ITKWindowsPython\ITK-bin\lib\ITKCommonPython.py", line 28, in swig_import_helper
    _mod = imp.load_module('_ITKCommonPython', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
itkTestDriver: Process exited with return value: 1

Change-Id: I0d313517218fb94320660b84ef8adbd6eb6cef67