COMP: member of dll interface class was declared with dll interface
Affected members: 'zero', 'one' and 'maxval'. Example error message:

C:\Jenkins\workspace\ITKWinVS14Ninja\ITK-src\Modules\ThirdParty\VNL\src\vxl\core\vnl/vnl_numeric_traits.h(75): error C2487: 'zero': member of dll interface class may not be declared with dll interface