COMP: Remove in-class {} member initializers of unique_ptr
Patch 5e2c49f9eb80e78903ce8f9fd2b5952062653cab causes the following
errors on GCC 7.4.1:
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘itk::NiftiImageIO::NiftiImageProxy’
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘itk::LBFGSBOptimizerHelper’
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘gdcm::SerieHelper’
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘itk::NiftiImageIO::NiftiImageProxy’
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘itk::GiftiMeshIO::GiftiImageProxy’
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application
of ‘sizeof’ to incomplete type ‘itk::GiftiMeshIO::GiftiImageProxy’

The issue has already been fixed in the past, see
d7c0128e99f02cfb58e8c447d175008b2b946a9f

All instances have been removed with the script:
for i in $(find Modules -type f)
do
  sed -i "s/\(unique_ptr.*\)\( *{}\)/\1/g" $i
done