COMP: No longer delete (`= delete`) PreFillDirection() function template
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2869
commit af32a779c4586304e52ddc27eb81656b949c9eeb ("COMP: Remove
unreachable code") "deleted" the `PreFillDirection()` function template
definition, by `= delete`. This appeared to cause compilation errors on
the following sites/builds:

  Site: RogueResearch7
  Build Name: Mac10.11-AppleClang-rel-x86_64-static
  Build Name: Mac10.11-AppleClang-dbg-x86_64-static

As reported by Jon Haitz Legarreta Gorroño at
https://github.com/InsightSoftwareConsortium/ITK/pull/2869#issuecomment-970306179

The error messages included:

    /Users/builder/externalModules/IO/NIFTI/test/itkNiftiImageIOTest.cxx:26:1: error: redefinition of 'PreFillDirection'
    PreFillDirection<1>()

The compilation error appears caused by Clang compiler issue "Bug 17537
- Explicit specialization of deleted function template not possible"
(https://bugs.llvm.org/show_bug.cgi?id=17537), reported by
jonathan.sauer, 2013-10-10, and fixed with Clang 3.9.

Worked around this compiler bug by removing `= delete`. Also removed the
declarations of the four `PreFillDirection()` specializations, as
suggested by Lee Newberg.