COMP: Update CastXML binary for Visual Studio 2019
Address:

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/include\intrin0.h(255,36): error G7F5978A3: constexpr declaration of '__builtin_assume_aligned' follows non-constexpr declaration

With an update to CastXML 2020-03-31 Git master and LLVM 10.0.0.