BUG: Add missing itk_expat_mangle.h install target
The problem was identified while trying to build a project that depends on an
installed version of ITK. I.e., ITK was built from source and then installed,
and the dependent project (in this case, SlicerExecutionModel) was configured
with ITK_DIR cmake variable. Here is the error:

//--------
c:\itk-install\include\itk-4.10\expatDllConfig.h(5): fatal error C1083: Cannot open include file: 'itk_expat_mangle.h': No such file or directory
//--------