BUG: Add semicolon after `ITK_EXERCISE_BASIC_OBJECT_METHODS` call
Add missing semicolon after `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro
call in test.

Fixes:
```
itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx:130:116: error: expected ';' after 'static_assert'
      shiftScalesEstimator, RegistrationParameterScalesFromPhysicalShift, RegistrationParameterScalesFromShiftBase)
                                                                                                                   ^
                                                                                                                   ;
```

Reported in:
https://open.cdash.org/viewBuildError.php?buildid=8785957

Oversight introduced in commit 165fb5b6fed0f7f9f0669570472905b9931e64b4.