COMP: Fix typo in bridge NumPy Python include
The typo caused errors when compiling external modules with additional PyBuffer
definitions, e.g., RTK:
```
In file included from /home/srit/src/itk/lin64-PythonWrapping/Wrapping/castxml_inputs/itkPyBufferRTK.cxx:16:
/home/srit/src/itk/itk/Modules/Bridge/NumPy/include/itkPyBuffer.h:30:10: fatal error: 'Python.h' file not found
   30 | #include <Python.h>
            |          ^~~~~~~~~~
```