COMP: Fix HDF5TransformIO compatibility with HDF 1.8
Use similar HDF5 C API method from the H5L: Link Interface.

This address:

  In file included from /scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx:21:0:
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx: In instantiation of 'void itk::HDF5TransformIOTemplate<TParametersValueType>::Read() [with TParametersValueType = double]':
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx:64:42:   required from here
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx:361:12: error: 'class H5::H5File' has no member named 'exists'
         if(! this->m_H5File->exists(fixedParamsName) ){
            ^
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx:368:12: error: 'class H5::H5File' has no member named 'exists'
         if(! this->m_H5File->exists(paramsName) ){
            ^
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx: In instantiation of 'void itk::HDF5TransformIOTemplate<TParametersValueType>::Read() [with TParametersValueType = float]':
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx:65:42:   required from here
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx:361:12: error: 'class H5::H5File' has no member named 'exists'
         if(! this->m_H5File->exists(fixedParamsName) ){
            ^
/scratch/dashboards/Linux-x86_64-gcc4.8-system/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx:368:12: error: 'class H5::H5File' has no member named 'exists'
         if(! this->m_H5File->exists(paramsName) ){

Co-Author: Bradley Lowekamp <blowekamp@mail.nih.gov>
Change-Id: I367ffbd9ead699f2c62b36bc7016e28afe0fa209