COMP: Need to propagate ITKGDCM
ITKGDCM needs to be propagated for external builds
fatal error: 'gdcmSerieHelper.h' file not found errors occur
in external applications builds.

Change-Id: Ie59bf129e5c6b0aaf832040f904aaecafc4fc738