BUG: Fix recent update of HDF5 (1.8.17)
When HDF5 was updated to 1.8.17 [1], itkhdf5/src/CMakeLists.txt was not
merged correctly. The missing line [2] lead to the following compilation
error:

.../ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5detect.c:87:19:
error: unknown type name ‘sigjmp_buf’
 #define H5JMP_BUF sigjmp_buf

[1] 5d643456fe7fba4a2a10739e4fd055b9912c7130
[2] https://svn.hdfgroup.uiuc.edu/hdf5/branches/hdf5_1_8_17/src/CMakeLists.txt

Change-Id: I1eecec3b3018e0af55c2ec5e2d961148922e2d4a