COMP: GaussianInterpolateImageFunction test narrowing
To address:

  D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion
  D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: image->SetPixel({{i, j}}, i + j);

Co-authored-by: Niels Dekker <N.Dekker@lumc.nl>