BUG: itkConfigure.h defines ITK_DEFAULT_MAX_THREADS
Missing header for definition of ITK_MAX_THREADS was affected by order
of include files in external programs using ITK.

ITK/Modules/Core/Common/include/itkThreadSupport.h:46:43: error: use of undeclared identifier 'ITK_DEFAULT_MAX_THREADS'
  constexpr std::size_t ITK_MAX_THREADS = ITK_DEFAULT_MAX_THREADS;