BUG: Remove declared but undefined method
Remove declared but undefined method from
`itk::GradientDifferenceImageToImageMetric`.

Fixes:
```
Loading ITKRegistrationCommon... Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/lazy.py", line 137, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 102, in itk_load_swig_module
    itk_load_swig_module(dep, namespace)
  File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 110, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 259, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/../ITKRegistrationCommonPython.py", line 13,
  in <module>
    from . import _ITKRegistrationCommonPython
ImportError: /home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/_ITKRegistrationCommonPython.so:
undefined symbol:
_ZNK3itk36GradientDifferenceImageToImageMetricINS_5ImageIsLj3EEES2_E26WriteGradientImagesToFilesEv
itkTestDriver: Process exited with return value: 1
```

raised for example in:
https://dev.azure.com/itkrobotlinuxpython/ITK.Linux.Python/_build/results?buildId=5739&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58be928-45a1-58e7-c1ad-04869565b3f4&l=13511

Raised when wrapping was added for the class in c41b29c.