COMP: BoundingBox call to MapContainer::Reserve
To address:

  ::GetCorners() [with TPointIdentifier = long unsigned int; int
  VPointDimension = 3; TCoordRep = float; TPointsContainer =
  itk::MapContainer<long unsigned int, itk::Point<float, 3> >;
  itk::BoundingBox<TPointIdentifier, VPointDimension, TCoordRep,
  TPointsContainer>::PointsContainer = itk::MapContainer<long unsigned
  int, itk::Point<float, 3> >]’:
  Wrapping/Modules/ITKCommon/itkBoundingBoxPython.cpp:9659:59:
  required from here
  /home/kitware/mattm/ITK/Modules/Core/Common/include/itkBoundingBox.hxx:125:23:
  error: ‘using ObjectType = class itk::MapContainer<long unsigned int,
  itk::Point<float, 3> > {aka class itk::MapContainer<long unsigned int,
  itk::Point<float, 3> >}’ has no member named ‘reserve’; did you mean
  ‘Reserve’?
     m_CornersContainer->reserve(NumberOfCorners);
        ~~~~~~~~~~~~~~~~~~~~^~~~~~~
           Reserve