COMP: Add missing itkMacro.h to itkSTLContainerAdapter.h
To address:

FAILED: Modules/Core/Common/CMakeFiles/ITKCommonHeaderTest6.dir/test/ITKCommonHeaderTest6.cxx.o
In file included from Modules/Core/Common/test/ITKCommonHeaderTest6.cxx:23:0:
/home/vsts/work/1/s/Modules/Core/Common/include/itkSTLContainerAdaptor.h:46:51:
error: ISO C++ forbids declaration of 'ITK_DISALLOW_COPY_AND_ASSIGN' with no type [-fpermissive]
   ITK_DISALLOW_COPY_AND_ASSIGN(STLContainerAdaptor);