ENH: Pin Python version in non-Python Azure pipelines
Pin Python version in non-Python Azure pipelines so that the required
Python package versions used match those used in the Azure pipelines
testing the Python wrapping.

Additionally, install the `lxml` Python package explicitly in the
Windows build.

Addresses:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\anyci\ctest_junit_formatter.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

raised in:
https://dev.azure.com/itkrobotwindow/ITK.Windows/_build/results?buildId=9122&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3f67303d-caa6-535b-2055-750b67f1a4bf&l=17