COMP: Fix CMake configuration for cmake versions without CMP0135
Fixes compilation error introduced by commit
797204114809ca99a39534497973b5f101343172 for versions prior to CMake 3.24:

CMake Error at Utilities/ClangFormat/DownloadClangFormat.cmake:47 (cmake_policy):
  Policy "CMP0135" is not known to this version of CMake.
Call Stack (most recent call first):
  CMake/ITKModuleClangFormat.cmake:17 (include)
  CMake/ITKModuleMacros.cmake:9 (include)
  CMakeLists.txt:146 (include)