COMP: Fix Nonunit/Review/test error: 'cindex': undeclared identifier
Fixed compile errors saying:

> error C2065: 'cindex': undeclared identifier

These compile errors were introduced by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4000
commit 7cda5badd0ae7802103421b6625e46bc956f6cb9
"COMP: Fix TransformPhysicalPointToContinuousIndex `nodiscard` warnings"