COMP: VTkGlue linker errors
Recent changes cause the following link error when
Module_ITKLevelSetsv4Visualization:BOOL=ON

Linking CXX executable ../../../../bin/ITKLevelSetsv4VisualizationTestDriver
/usr/bin/ld: CMakeFiles/ITKLevelSetsv4VisualizationTestDriver.dir/itkVTKVisualizeLevelSetsInteractivePauseTest.cxx.o:
undefined reference to symbol
'_ZNK3itk18VTKImageExportBase32GetPropagateUpdateExtentCallbackEv'
/usr/bin/ld: note:
'_ZNK3itk18VTKImageExportBase32GetPropagateUpdateExtentCallbackEv' is
defined in DSO /home/lorensen/ProjectsGIT/ITKGerrit-linux/lib/libITKVTK-4.9.so.1
so try adding it to the linker command line
/home/lorensen/ProjectsGIT/ITKGerrit-linux/lib/libITKVTK-4.9.so.1:
could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [bin/ITKLevelSetsv4VisualizationTestDriver] Error 1
make[1]: *** [Modules/Segmentation/LevelSetsv4Visualization/test/CMakeFiles/ITKLevelSetsv4VisualizationTestDriver.dir/all]
Error 2

----------------------------------
git bisect commit identified this commit:

Author: Zach Williamson <zachary-williamson@uiowa.edu>
Date:   Wed Jul 15 10:39:04 2015 -0500

    ENH: Use new linking system macros

    This is a work-in-progress to demonstrate using the new linking system
    (DEPENDS, COMPILE_DEPENDS, PRIVATE_DEPENDS etc.)

    Most changes so far are using private_depends where applicable to reduce the
    total number of links being created (since public dependencies are linked
    recursively while private dependencies are not)

    Change-Id: I41bed74b8d6ed508f2014163854799ed0ef17919

Change-Id: I7aa45520ae4da8d85246c661bc5b0c741d1e31cb