COMP: Fix missing alias for iterator types
Fixes compile errors introduced by cfd3cad35d4496b2482141c0f0cba899ffb073d5, e.g.:
```
C:\src\itk\ITK-main\Modules\Filtering\FFT\include\itkFFTWComplexToComplex1DFFTImageFilter.hxx(191,11): error C2065: 'inputBufferIt' : undeclared identifier [C:\src\itk\2019-main-Shared-Debug-FFTWON\Modules\Filtering\FFT\src\ITKFFT.vcxproj
C:\src\itk\ITK-main\Modules\Filtering\FFT\include\itkFFTWComplexToComplex1DFFTImageFilter.hxx(189,80): error C2061: syntax error : identifier 'PixelType' [C:\src\itk\2019-main-Shared-Debug-FFTWON\Modules\Filtering\FFT\src\ITKFFT.vcxproj]
```