COMP: Float narrowing conversion in BSpline class initialization
To address build error uncovered by Windows Python wrapping:

c:\itk\modules\filtering\biascorrection\include\itkN4BiasFieldCorrectionImageFilter.h(415): error C2397: conversion from 'double' to 'itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::RealType' requires a narrowing conversion
c:\itk\modules\filtering\imagegrid\include\itkBSplineScatteredDataPointSetToImageFilter.h(362): error C2397: conversion from 'double' to 'itk::BSplineScatteredDataPointSetToImageFilter<itk::PointSet<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2,itk::DefaultStaticMeshTraits<TPixelType,2,2,float,float,TPixelType>>,itk::Image<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2>>::RealType' requires a narrowing conversion
        with
        [
            TPixelType=itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType
        ]
c:\itk\modules\filtering\imagegrid\include\itkBSplineScatteredDataPointSetToImageFilter.hxx(40): note: while compiling class template member function 'itk::BSplineScatteredDataPointSetToImageFilter<itk::PointSet<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2,itk::DefaultStaticMeshTraits<TPixelType,2,2,float,float,TPixelType>>,itk::Image<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2>>::BSplineScatteredDataPointSetToImageFilter(void)'
        with
        [
            TPixelType=itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType
        ]
c:\itk\modules\filtering\imagegrid\include\itkBSplineScatteredDataPointSetToImageFilter.h(142): note: see reference to function template instantiation 'itk::BSplineScatteredDataPointSetToImageFilter<itk::PointSet<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2,itk::DefaultStaticMeshTraits<TPixelType,2,2,float,float,TPixelType>>,itk::Image<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2>>::BSplineScatteredDataPointSetToImageFilter(void)' being compiled
        with
        [
            TPixelType=itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType
        ]
c:\itk\modules\filtering\biascorrection\include\itkN4BiasFieldCorrectionImageFilter.h(137): note: see reference to class template instantiation 'itk::BSplineScatteredDataPointSetToImageFilter<itk::PointSet<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2,itk::DefaultStaticMeshTraits<TPixelType,2,2,float,float,TPixelType>>,itk::Image<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2>>' being compiled
        with
        [
            TPixelType=itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType
        ]