COMP: Fix VS2017 compilation regression
With VS2017 following compile errors occur:
3>itkBuildInformation.cxx
3>c:\dev\itk-git\modules\core\common\include\itkthreadsupport.h(63): error C2131: expression did not evaluate to a constant
3>c:\dev\itk-git\modules\core\common\include\itkthreadsupport.h(63): note: failure was caused by unevaluable pointer value

Chromium had the same issue, and they had to settle for const instead of constexpr:
https://chromium-review.googlesource.com/c/crashpad/crashpad/+/585452

Change-Id: I42ec0d50430d34f6d6f1bbd429dff49ef91c34b6