COMP: Specify type in LiThresholdCalculator min call
To address:

  In file included from /home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.h:87:0,
                 from Wrapping/Typedefs/itkLiThresholdCalculatorSwigInterface.h:19,
                 from Wrapping/Modules/ITKThresholding/itkLiThresholdCalculatorPython.cpp:3371:
/home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.hxx: In instantiation of ‘void itk::LiThresholdCalculator<THistogram, TOutput>::GenerateData() [with THistogram = itk::Statistics::Histogram<float>; TOutput = float]’:
Wrapping/Modules/ITKThresholding/itkLiThresholdCalculatorPython.cpp:8112:1:   required from here
/home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.hxx:65:34: error: no matching function for call to ‘min(const MeasurementType&, double)’
   const double bin_min = std::min(histogram->GetBinMin(0,0), 0.0);