COMP: Add -D_LARGEFILE64_SOURCE for HDF5 with Emscripten-1.
This addresses the build error:

/usr/src/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDstdio.c:195:5: error: use of undeclared identifier 'off64_t'
    MAXADDR,                                    /*maxaddr               */
    ^

with Emscripten 1.34.3 where CMAKE_SYSTEM is Emscripten-1
because _LARGEFILE64_SOURCE needs to be defined for off64_t to be defined.

Change-Id: Ia84794ff6a240c3f977c2d028eb2ffb18032aeb2