STYLE: Remove unused "itkFrequencyImageRegion*IteratorWithIndex.h" files
Both `FrequencyImageRegionIteratorWithIndex` and
`FrequencyImageRegionConstIteratorWithIndex` appear unused and untested.
Attempts to use them would trigger compile errors.

An attempt to use `FrequencyImageRegionIteratorWithIndex` triggered:

    error C3210: 'ImageRegionIteratorWithIndex<itk::Image<int,2> >': a member using-declaration can only be applied to a base class member

An attempt to use `FrequencyImageRegionConstIteratorWithIndex` triggered:

    error C2679: binary '=': no operator found which takes a right-hand operand of type 'const itk::Point<T,3>' (or there is no acceptable conversion)

This commit removes their header files. It also removes the suggestion to use
`FrequencyImageRegionIteratorWithIndex` from the documentation of
UnaryFrequencyDomainFilter.