COMP: Fix additional missing alias for iterator types
This complements 920c6818db15eaf60cf9bbf02eec74e235c02d04 which left the
following error behind:
```
C:\src\itk\ITK-main\Modules\Filtering\FFT\include\itkFFTWForward1DFFTImageFilter.hxx(161,68): error C2061: syntax error : identifier 'PixelType' [C:\src\itk\2019-main-Shared-Debug-FFTWON\Modules\Filtering\FFT\src\ITKFFT.vcxproj]
```