COMP: Work around GCC-4.8 error converting to OptimizerParametersHelper
Worked around an apparent compiler bug in GCC 4.8 (which seems to be
fixed with GCC 4.9.2), causing a compile error from GCC 4.8.4 at
https://open.cdash.org/viewBuildError.php?buildid=6897873 saying:

> Core/Common/include/itkOptimizerParameters.h:53:3:
> error: converting to 'std::unique_ptr<itk::OptimizerParametersHelper>'
> from initializer list would use explicit constructor...

Reported by Bradley Lowekamp (blowekamp) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2114#issuecomment-733741732