COMP: Use _timezone for Visual Studio
VS2015 does not have timezone defined in time.h. VS2014 header reports timezone not available under /clr:pure use _timezone

Error Reported
C:\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Omtime.c(226):
error C2065: 'timezone': undeclared identifier
[C:\build\itk-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\itkhdf5.vcxproj]

Change-Id: I75c121555485937d784a40fae22908541a22bc7a