COMP: Fix compile errors on VS2017
They were introduced around the time C++17 was enabled.
The first error message was:

m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): error C2244: 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector': unable to match function definition to an existing declaration
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(473): note: see declaration of 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: definition
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(const itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::IndexType &) const'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: existing declarations
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(const itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::IndexType &) const'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::InstanceIdentifier) const'