BUG: CASTXML fails with aggressive optimizer flags
Incompatibilties with advanced compiler optimization
flags are not properly managed with CASTXML.

export FAILING_FLAG="-mfma"

ITK-bld/Wrapping/Modules/ITKCommon && \\
    ITK-bld/Wrapping/Generators/CastXML/castxml/bin/castxml \\
    -o ITK-bld/Wrapping/itkPointSetToImageFilter.xml --castxml-gccxml \\
    --castxml-start _wrapping_ \\
    --castxml-cc-gnu "(" /usr/bin/c++ ${FAILING_FLAG} ")" \\
    -w \\
    -c @ITK-bld/Wrapping/ITKCommon.castxml.inc ITK-bld/Wrapping/itkPointSetToImageFilter.cxx

In file included from ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/Core:391:
ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/arch/AVX/PacketMath.h:169:54: error: invalid output size for constraint '+x'
  __asm__("vfmadd231ps %[a], %[b], %[c]" : [c] "+x" (res) : [a] "x" (a), [b] "x" (b));
                                                     ^
ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/arch/AVX/PacketMath.h:179:54: error: invalid output size for constraint '+x'
  __asm__("vfmadd231pd %[a], %[b], %[c]" : [c] "+x" (res) : [a] "x" (a), [b] "x" (b));
2 errors generated.

Expand the removal of "-fopenmp" to also include the identified
compiler optimization flags.