COMP: Fix wrapping with Core only
When buidling with Core only, some types should not be wrapped, as this would result
in the following error:

[ 39%] Generating vnl_matrix.xml
cd /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon && ../../Generators/GccXML/gccxml/bin/gccxml -fxml-start=_cable_ -fxml=/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.xml --gccxml-gcc-options /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/gcc_xml.inc -DCABLE_CONFIGURATION -DITK_MANUAL_INSTANTIATION /home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.cxx
/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.cxx:2:38: error: itkStatisticsLabelObject.h: No such file or directory
/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.cxx:16:29: error: itkLevelSetNode.h: No such file or directory
/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.cxx:17:39: error: itkFlatStructuringElement.h: No such file or directory
/home/mpopoff/repo/buildlight/Wrapping/Modules/ITKCommon/vnl_matrix.cxx:20:25: error: itkLabelMap.h: No such file or directory

itkStatisticsLabelObject.h was included for all the modules, in fact is only needed for the two following groups:
- LabelMap
- ImageFusion
Instead of always including it, it is now only included for the two groups.

Change-Id: I080766a815a1d9edd3aeb8998facdea6a30c824d