Fix build errors in itkImageToParametricSpaceFilter.
This was broken with this commit 38d629929b3aad8cbe9.

Scanning dependencies of target itkBasicFiltersHeaderTest
[ 64%] Building CXX object
Testing/Code/BasicFilters/CMakeFiles/itkBasicFiltersHeaderTest.dir/itkBasicFiltersHeaderTest.cxx.o
In file included from
/var/datad/ITKgh/Testing/Code/BasicFilters/itkBasicFiltersHeaderTest.cxx:152:
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx: In
member function ‘void itk::ImageToParametricSpaceFilter<TInputImage,
TOutputMesh>::GenerateData()’:
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:121:
error: expected nested-name-specifier
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:121:
error: expected ‘(’
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:121:
error: expected ‘;’
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:126:
error: ‘it’ was not declared in this scope
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:140:
error: expected nested-name-specifier
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:140:
error: expected ‘(’
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:140:
error: expected ‘;’
/var/datad/ITKgh/Code/BasicFilters/itkImageToParametricSpaceFilter.txx:142:
error: ‘it’ was not declared in this scope
make[2]: ***
[Testing/Code/BasicFilters/CMakeFiles/itkBasicFiltersHeaderTest.dir/itkBasicFiltersHeaderTest.cxx.o]
Error 1
make[1]: ***
[Testing/Code/BasicFilters/CMakeFiles/itkBasicFiltersHeaderTest.dir/all] Error 2
make: *** [all] Error 2

Change-Id: I902a42b6e724e7dca490655187792e44576aa0e7