COMP: Fix warnings and missing include
This patch addresses the following warning:
itkBinShrinkImageFilter.hxx:117:54: warning: declaration of
'OffsetValueType' shadows a global declaration

by removing the unused type.

And addresses compilation errors related to:
itkBinShrinkImageFilter.hxx(157): error C2039: 'multiplies' : is not a
member of 'std'

by including the functional header.

Additionally the initial accumulate is cast to size_t to ensure
correct implicit template parameters to accumulate.

Change-Id: I69c5b78b96c2801ce3ffc85c271158464a1a7476