BUG: Build BridgeNumPy with Visual Studio.
ITK-3371

Addresses:

  {{18>d:\workspace\projetcs\itk\modules\remote\bridgenumpy\include\itkPyBuffer.hxx(61):
  error C2466: cannot allocate an array of constant size 0
  18>d:\workspace\projetcs\itk\modules\remote\bridgenumpy\include\itkPyBuffer.hxx(61):
  error C2133: 'dimensions' : unknown size
  18>d:\workspace\projetcs\itk\modules\remote\bridgenumpy\include\itkPyBuffer.hxx(79):
  error C2057: expected constant expression
  18>d:\workspace\projetcs\itk\modules\remote\bridgenumpy\include\itkPyBuffer.hxx(79):
  error C2466: cannot allocate an array of constant size 0
  18>d:\workspace\projetcs\itk\modules\remote\bridgenumpy\include\itkPyBuffer.hxx(79):
  error C2133: 'reverseDimensions' : unknown size}}

Change from Nir Hal.

Change-Id: Ie787e8f4ce922712c318d58df679b28a597c0d2d