COMP: Fix PythonReadDicomTagTest on OS X
We need to clean up strings on OS X.
The argument was "std::__1::string"
instead of the expected "std::string".

This fixes the following error:

Traceback (most recent call last):
  File "/scratch/dashboards/MacOSX-WrapITK/ITK/Wrapping/Generators/Python/Tests/ReadDicomAndReadTag.py", line 63, in <module>
    found, name2 = dicomIO.GetValueFromTag("0010|0010", "")
TypeError: in method 'itkGDCMImageIO_GetValueFromTag', argument 3 of type 'std::string &'

Change-Id: I2cb29498bb838aa77f8064d8f07710c87c744bfc