COMP: Fix support itk::VectorContainer<TElementIdentifier, bool>
Fixed `itk::VectorContainer<TElementIdentifier, TElement>` compile errors
for `TElement` = `bool`:

    itkVectorContainer.h(137): error C2039: 'data': is not a member of 'std::vector<TElement,std::allocator<_Ty>>'
    itkVectorContainer.h(210): error C2440: 'return': cannot convert from 'std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>' to 'bool &'
    itkVectorContainer.hxx(40): error C2440: 'return': cannot convert from 'std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>' to 'bool &'

Note: These compile errors are from Visual C++ 2017, trying to compile the added GTest before fixing `itk::VectorContainer`.

Also fixes Azure.Mac-531/Darwin-Build961 errors:

    no member named 'emplace' in 'std::vector<bool>'
    no member named 'emplace_back' in 'std::vector<bool>'
    no matching constructor for initialization of 'std::vector<bool>'