COMP: Add missing mutex include to itkImageToHistogramFilter.h
To address:

2018-11-07T00:56:29.5022052Z D:/a/1/s/Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h:138:8: error: no type named 'mutex' in namespace 'std'
2018-11-07T00:56:29.5188235Z   std::mutex m_Mutex;%