STYLE: Removed unused private EventObject::EventFactoryFunction type
Removed unused `EventFactoryFunction` type, in response to Sandro Queiros,
who reported VS2015 compile errors at forum topic "Build ITK 5.0 in Windows",
https://discourse.itk.org/t/build-itk-5-0-in-windows/1748 saying:

    itkEventObject.h(96): error C2071: ‘itk::EventObject::EventFactoryFunction’: illegal storage class

Follow-up to the removal of an `std::map< std::string, EventFactoryFunction >`,
by Luis Ibanez, 2001-11-12, commit 16b9d79d8837b62b1d51394614b2b10aa277c58e