BUG: Do not run KWStyle Git config on a release tarball.
In a release tarball archive, the .git directory does not exist. Only set the
Git configuration path to KWStyle if the ITK source tree is a Git repository.

This addresses the error:

  error: could not lock config file .git/config: No such file or directory

Change-Id: I524d77eb86979cc0137bd775d7a30e18bc3318ac