COMP: ofstream requires explicit const char *
On Clang 3.8:

  /home/matt/src/ITKIsotropicWavelets/test/itkIsotropicWaveletFrequencyFunctionTest.cxx:82:17: error: no matching constructor for initialization of 'std::ofstream' (aka 'basic_ofstream<char>')
    std::ofstream ofs(profileDataRootPath + "_" + waveletTypeName +  "_" + n2s(inputBands) + ".txt", std::ofstream::out);