COMP: Replace np.bool with np.bool_
- The alias np.bool was officially deprecated in NumPy 1.20.0.  ￼
- The removal (i.e. making np.bool inaccessible / raising AttributeError) occurred in NumPy 1.24.0.

As was done upstream in a63750180be6b8e5af548f8dbf7a337221136c20

For:

E   AttributeError: module 'numpy' has no attribute 'bool'.
E   `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E   The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E       https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations