COMP: Add missing semicolon to macro statement end in tests
Add missing semicolon to macro statement end in tests.

Fixes:
```
Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx:252:49:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_TRUE(numPixelsDifferent <= 10)
                                                ^
                                                ;
Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx:279:29:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_TRUE(fptr)
                            ^
                            ;
2 errors generated.
```

and
```
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:718:101:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_EQUAL(itk::TemporalProcessObjectTest::m_CallStack.size(), correctCallStack.size())
                                                                                                    ^
                                                                                                    ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:754:101:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_EQUAL(itk::TemporalProcessObjectTest::m_CallStack.size(), correctCallStack.size())
                                                                                                    ^
                                                                                                    ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:789:101:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_EQUAL(itk::TemporalProcessObjectTest::m_CallStack.size(), correctCallStack.size())
                                                                                                    ^
                                                                                                    ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:822:86:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_EQUAL(tpo1->GetOutput()->GetRequestedTemporalRegion(), emptyRegion)
                                                                                     ^
                                                                                     ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:826:79:
error: expected ';' after static_assert
                        tpo1->GetOutput()->GetLargestPossibleTemporalRegion())
                                                                              ^
                                                                              ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:827:90:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_TRUE(!(tpo1->GetOutput()->GetRequestedTemporalRegion() == emptyRegion))
                                                                                         ^
                                                                                         ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:840:53:
error: expected ';' after static_assert
                        ITK_INFINITE_FRAME_DURATION)
                                                    ^
                                                    ;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:841:95:
error: expected ';' after static_assert
  ITK_TEST_EXPECT_EQUAL(tpo1->GetOutput()->GetRequestedTemporalRegion().GetFrameDuration(), 1)
                                                                                              ^
                                                                                              ;
8 errors generated.
```

raised for example in:
https://open.cdash.org/viewBuildError.php?onlydeltap&buildid=8966062

Introduced inadvertently in commit c313059.