COMP: Add missing semicolon to `itkExceptionMacro` statement end
Add missing semicolon to `itkExceptionMacro` statement end.

Fixes:
```
In file included from Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx:19:
Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h:171:87:
error: expected ';' after static_assert
      itkExceptionMacro(<< "No target point set. Cannot set the target reached mode.")
                                                                                      ^
										      ;
Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h:181:87:
error: expected ';' after static_assert
      itkExceptionMacro(<< "No target point set. Cannot set the target reached mode.")
                                                                                      ^
                                                                                      ;
Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h:199:87:
error: expected ';' after static_assert
      itkExceptionMacro(<< "No target point set. Cannot set the target reached mode.")
                                                                                      ^
                                                                                      ;
Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h:205:87:
error: expected ';' after static_assert
      itkExceptionMacro(<< "No target point set. Cannot set the target reached mode.")
                                                                                      ^
                                                                                      ;
4 errors generated.
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=7829663