COMP: Add `template` to TransformPhysicalPointToContinuousIndex in tests
Added missing `template` keywords to TransformPhysicalPointToContinuousIndex
calls in Nonunit/Review tests.

Addressed compile errors from Ubuntu-22.04-gcc11.2-TBB-Debug saying:

> error: expected primary-expression before '>' token

These compile errors were introduced by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4000
commit 7cda5badd0ae7802103421b6625e46bc956f6cb9
"COMP: Fix TransformPhysicalPointToContinuousIndex `nodiscard` warnings"