COMP: Fix typo (compile error) in `PhilipsRECImageIO` constructor
Fixed a compile error, which appeared when enabling `Module_ITKIOPhilipsREC`:

> itkPhilipsRECImageIO.cxx(390,3): error C3861: 'iff': identifier not found

This obvious typo was introduced with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3664
commit 2b1b5312fadf1a156882d06dc2e7c6b2a2290044 "STYLE: Remove space between
class and member names (follow-up)", and reported by Bradley Lowekamp.