COMP: missing #include <condition_variable>
Fixing compile error:
Modules/Segmentation/LevelSetsv4Visualization/test/itkVTKVisualizeLevelSetsInteractivePauseTest.cxx:43:8: error: 'condition_variable' in namespace 'std' does not name a type

Change-Id: Ie5a2959e8947ad0717450be1ef15e0f51792a7e4