BUG: Use new VNL include directory variables.
These variables changed in recent upstream VNL. Keep the old variables for
backwards compatibility. Addresses:

  /home/matt/src/vxl/vcl/vcl_compiler.h:121:31: fatal error:
  vcl_config_manual.h: No such file or directory

  /home/matt/src/vxl/core/vnl/vnl_error.h:10:28: fatal error:
  vnl/vnl_export.h: No such file or directory

with ITK_USE_SYSTEM_VXL enabled.

Change-Id: I7c8ea9bbb195e176cde3e8969075bef4906073c2