COMP: Fix BinomialBlurImageFilter error, num_reps undeclared identifier
Fixed Debug compilation erors saying:

> error C2065: 'num_reps': undeclared identifier

Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3996
commit cd97879e6bfec6cd9a33a3dd374d68cf4ff4303e "COMP: Remove unused variables"

The `itkDebugMacro` statement that got this error does not seem to be of
interest anymore.