BUG: Fix remotes maintenance scripts
Fix remotes maintenance scripts:
- Fix scripts input arguments `command not found` error adding the `test`
  command over each argument.Fixes:
  ```
  ./Utilities/Maintenance/ApplyScriptToRemotes.sh: line 82:
  UpdateTestingMacrosNames: command not found
  ./Utilities/Maintenance/ApplyScriptToRemotes.sh: line 82: ENH: Update
  ITK testing macros names: command not found
  ```

and idem for `UpdateRequiredITKVersionInRemoteModules.sh`.

Avoid the script continuing its execution if not all input parameters have
been provided.

- Fix the `git add` command failing when not finding any file extension
  that matches the filters. This was causing that even files whose
  extension matched any of those before the missing one were not being
  added. Fixes:
  ```
  fatal: pathspec './*.c' did not match any files
  fatal: pathspec './*.rst' did not match any files
  ```
  Filters are now applied individually so that if one is not
  found/fails, the rest can still be added. Also, `stdout` and `stderr`
  are redirected to `/dev/null` to avoid excessive, additional
  verbosity.

- Fix the commit message not being correctly processed: quotes within
  the script were missing (in addition to the quotes in the input
  argument so that the script considers it as a single argument).
  Fixes:
  ```
  error: pathspec 'Update' did not match any file(s) known to git.
  error: pathspec 'ITK' did not match any file(s) known to git.
  error: pathspec 'testing' did not match any file(s) known to git.
  error: pathspec 'macros' did not match any file(s) known to git.
  error: pathspec 'names' did not match any file(s) known to git.
  ```

- Fix the `ITK-build` directory not being removed for being non empty.
  Fixes:
  ```
  rm: cannot remove '../../../ITK-build': Directory not empty
  ```