COMP: Fix compile error due to missing itk:: prefix for MakeFilled
Sample error message:

T:\Dashboard\ITK\Modules\Nonunit\Review\test\itkImageFunctionTest.cxx(137,17): error C2065: 'MakeFilled': undeclared identifier [T:\Dashboard\ITK-build\Modules\Nonunit\Review\test\ITKReviewTestDriver.vcxproj]