COMP: Fix DiffeomorphicDemonsRegistration Wrapping
The changes introduced to wrap more combinations of vector images types
(see 2260f30a996bc606790305a5702b292bdac3b561) created in the case of
this filter combinations with: image dim != vector dim.

The fix just goes back to the initial situation for this specific
filter, by defining manually the wrapping templates.

For the record, the build failed with the following error:

[3817/4135] Generating itkDiffeomorphicDemonsRegistrationFilter.xml
FAILED: cd /home/popoff/repo/builds/ITK/Wrapping/Modules/ITKReview && /home/popoff/repo/builds/ITK/Wrapping/Generators/GccXML/llvm/bin/castxml -w -c -o /home/popoff/repo/builds/ITK/Wrapping/Modules/ITKReview/itkDiffeomorphicDemonsRegistrationFilter.xml @/home/popoff/repo/builds/ITK/Wrapping/Modules/ITKReview/gcc_xml.inc /home/popoff/repo/builds/ITK/Wrapping/Modules/ITKReview/itkDiffeomorphicDemonsRegistrationFilter.cxx
In file included from /home/popoff/repo/builds/ITK/Wrapping/Modules/ITKReview/itkDiffeomorphicDemonsRegistrationFilter.cxx:5:
In file included from /home/popoff/repo/ITK/Modules/Core/Common/include/itkContinuousIndex.h:22:
In file included from /home/popoff/repo/ITK/Modules/Core/Common/include/itkIndex.h:23:
In file included from /home/popoff/repo/ITK/Modules/Core/Common/include/itkMath.h:33:
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:580:11: error: no viable conversion from 'UniqueType_unsigned_int<2>' to 'UniqueType_unsigned_int<3>'
      DT1 a = DT2();
          ^   ~~~~~
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:585:3: note: in instantiation of member function 'itk::Concept::SameDimension<3, 2>::Constraints::constraints' requested here
  itkConceptConstraintsMacro();
  ^
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:62:36: note: expanded from macro 'itkConceptConstraintsMacro'
  typedef Enforcer< & Constraints::constraints > EnforcerInstantiation
                                   ^
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:110:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'DT2' (aka 'UniqueType_unsigned_int<2U>') to 'const itk::Concept::Detail::UniqueType_unsigned_int<3> &' for 1st argument
struct UniqueType_unsigned_int {};
       ^
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:580:11: error: no viable conversion from 'UniqueType_unsigned_int<3>' to 'UniqueType_unsigned_int<2>'
      DT1 a = DT2();
          ^   ~~~~~
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:585:3: note: in instantiation of member function 'itk::Concept::SameDimension<2, 3>::Constraints::constraints' requested here
  itkConceptConstraintsMacro();
  ^
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:62:36: note: expanded from macro 'itkConceptConstraintsMacro'
  typedef Enforcer< & Constraints::constraints > EnforcerInstantiation
                                   ^
/home/popoff/repo/ITK/Modules/Core/Common/include/itkConceptChecking.h:110:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'DT2' (aka 'UniqueType_unsigned_int<3U>') to 'const itk::Concept::Detail::UniqueType_unsigned_int<2> &' for 1st argument
struct UniqueType_unsigned_int {};
       ^
2 errors generated.

Change-Id: Ie4bfb747af2a32860f7c75431bd1ddf47b86a536