COMP: VS15 compiler fix
Error C2338: container adaptors require consistent types

The element type was NodeType and the
predicate was std::greater<NodePairType>
This discrepancy is fixed by using NodePairType as the element.

Change-Id: Icf1e4fae2eaf83589d1b99c9e2c65ce315e23c2a