COMP: Fix Nonunit/Review/test error: ContinuousIndexType is not a member
Fixed compile errors saying:

> error C2039: 'ContinuousIndexType': is not a member of 'itk::ContinuousIndex'

These compile errors were introduced by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4000
commit 7cda5badd0ae7802103421b6625e46bc956f6cb9
"COMP: Fix TransformPhysicalPointToContinuousIndex `nodiscard` warnings"