COMP: Tests should not have "using namespace itk".
Tests and programs should not have "using namespace itk".

This may be causing the following compile error on some 64 bit
systems:

xlocnum(590) : error C2872: 'uintptr_t' : ambiguous symbol
  could be 'vadefs.h(50) : unsigned __int64 uintptr_t'
  modules\core\common\include\itkIntTypes.h(118) : itk::uintptr_t'

Change-Id: Id061ec19d1b0deaeea9248c108042e6afbae38db