COMP: itk::Math perfect forward return type
This addresses errors such as:

  error: 'auto' not allowed in function return type

with C++11 and ITK_WRAP_PYTHON=1 on macOS.

As discussed here:

   http://stackoverflow.com/questions/9864125/c11-how-to-alias-a-function

`using` is preferred when the names are the same. Do explicit perfect
forwarding for cuberoot since the name changed.

Change-Id: If363adb290b6bc5ebe8e17b1763c82b593b67c80