BUG: Address tab completion with IPython >= 5.0.0
Address the following error that occurs with IPython >= 5.0.0 when tab completion is attempted:

In [3]: itk.Image[Traceback (most recent call last):
  File "/home/matt/bin/venvs/itk/local/lib/python2.7/site-packages/IPython/core
    self.matches.extend(matcher(text))
  File "/home/matt/bin/ITK-Wrap-MinSizeRel/Wrapping/Generators/Python/itkExtras
    textUntilCursor = ip.Completer.readline.get_line_buffer()[:ip.Completer.re]
AttributeError: 'NoneType' object has no attribute 'get_line_buffer'

Newer versions of IPython on based on the Python Prompt Toolkit and do not use readline.

Returned matches also need to be of type unicode.

Change-Id: Ia649b72e1b11adf9a7a62632ab878c5bd0cf3ce8