COMP: Identify numpy bool attr as bool instead of bool8
For:

Traceback (most recent call last):
  File "/home/matt/src/ITK/Wrapping/Generators/Python/Tests/test_metadata.py", line 26, in <module>
    import itk
  File "/home/matt/src/ITK/build-python/Wrapping/Generators/Python/itk/__init__.py", line 28, in <module>
    from itk.support.extras import *
  File "/home/matt/src/ITK/build-python/Wrapping/Generators/Python/itk/support/extras.py", line 37, in <module>
    import itk.support.types as itkt
  File "/home/matt/src/ITK/build-python/Wrapping/Generators/Python/itk/support/types.py", line 178, in <module>
    ) = itkCType.initialize_c_types_once()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/src/ITK/build-python/Wrapping/Generators/Python/itk/support/types.py", line 143, in initialize_c_types_once
    _B: "itkCType" = itkCType("bool", "B", np.dtype(np.bool8))
                                                    ^^^^^^^^
  File "/home/matt/src/ITK/.pixi/envs/python/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?