BUG: Compilation problem with GCC 4.1 and explicit instantiation
The patch demonstrates the a compilation error when trying to
explicitly instantiate ITK classes as done in SimpleITK with GCC
version 4.1.

itkImageRegion.h: In instantiation of ‘const unsigned int itk::ImageRegion<1u>::ImageDimension’:
itkImageRegion.h:92: instantiated from ‘itk::ImageRegion<1u>’
itkImageRegionExplicitTest.cxx:22: instantiated from here
itkImageRegion.h:92: error: explicit instantiation of ‘itk::ImageRegion<1u>::ImageDimension’ but no definition available

This use to work with ITK 4.8, the change is related to the change of
the static constant macros from enums.

Change-Id: I7ff0db18a175dacc7e92b060130805e34cda809e