COMP: Fix older gcc build error including "cstddef" for "ptrdiff_t"
This commit fixes a regression likely introduced in c173dfd80 (STYLE: Remove
`std::` prefix from types that work without it) to support building ITK
wheels using manylinux_2_24 providing gcc 6.3.

It fixes build error like the following:

  In file included from /work/ITK-source/ITK/Modules/Core/Common/include/itkImageRegion.h:33:0,
                   from /work/ITK-source/ITK/Modules/Core/Common/include/itkMultiThreaderBase.h:35,
                   from /work/ITK-source/ITK/Modules/Core/Common/src/itkTotalProgressReporter.cxx:19:
  /work/ITK-source/ITK/Modules/Core/Common/include/itkSize.h:242:27: error: ‘ptrdiff_t’ does not name a type
     using difference_type = ptrdiff_t;
                             ^~~~~~~~~