COMP: Missing required base class API component
The GetNumberOfFixedParameters is required to be
overriden from the base class. Other similar
interface were previously implemented, so this
should be implmented to provide consistent
API components.

Modules/Core/Transform/include/itkMultiTransform.h:263:34:
error: 'GetNumberOfFixedParameters' marked 'override' but does not
override any member functions
  virtual NumberOfParametersType GetNumberOfFixedParameters() const ITK_OVERRIDE;

Change-Id: I7f2565cd41c87c6d683f90572abfa7de046aa3ad