COMP: Fix `abs` method not being found
Fix `abs` method not being found:
- Include `itkMath.h` to have `abs` available.
- Use the standard library `abs` where ITK objects are not used.

Fixes:
```
\Modules\Numerics\FEM\src\itkFEMElement3DC0LinearHexahedron.cxx(223):
error C2039:
'Math': is not a member of 'itk' [M:\Dashboard\ITK-build\Modules\Numerics\FEM\src\ITKFEM.vcxproj]
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=7619926

Introduced in 716822e.