COMP: update VTKTetrahedralMeshReader to enum class
This is required to build with legacy disabled. Message was:

m:\dashboard\itk\modules\registration\fem\test\itkVTKTetrahedralMeshReader.hxx(55): error C2039: 'CellsAllocatedDynamicallyCellByCell': is not a member of 'itk::Mesh<MeshPixelType,3,itk::DefaultStaticMeshTraits<TPixelType,3,3,float,float,TPixelType>>' [M:\Dashboard\ITK-build\Modules\Registration\FEM\test\ITKFEMRegistrationTestDriver.vcxproj]