COMP: add set methods for member variables where missing.
Users of itkMatrix for dimensions and types not provided in
VNLInstantiation/src were required to either
1) Use VNL_MATRIX_FIXED_INSTANTIATE(T, M, N)
or
2) include vnl_matrix_fixed.txx

This patch adds the include for vnl_matrix_fixed.txx to
itkMatrix.h. Also, the test, itkMatrixTest was using 1) and that is no
longer needed..

This addresses the Jira Ticket:
https://itk.icts.uiowa.edu/jira/brows/ITK-2977
reported by David Doria, motivated by a user who tried to instantiate
itk::Matrix<double, 512, 3>.
The user saw a link error:
undefined reference to `vnl_matrix_fixed<double, 512u, 3u>::fill(double)'

Change-Id: Id7337c6b258bd4224a2fb91821aa4844b135348b