COMP: Remove CTAD because of clang "error: member reference base" bug
Removed a few cases of class template argument deduction, because of compile
errors from RogueResearch17/Mac10.15-AppleClang-rel, saying:

> error: member reference base type 'ImageRegionRange' is not a structure or union

Caused by clang Bug 39663 "Class template argument deduction with deduced type
fails when accessing member", reported by Baruch, 2018-11-14 at
https://bugs.llvm.org/show_bug.cgi?id=39663 and fixed on 2020-10-08. The fix
appears to be included with LLVM Clang 12.0.0.

This partially reverts pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3989
commit 8ee4d9a410556cd1619c188e8e588710805b2da8 "STYLE: Use C++17 CTAD for
`ImageRegionRange`"