COMP: Remove spare closing bracket
Remove spare closing bracket.

Left behind inadvertently in commit 2bd9f0a.

Fixes:
```
T:\Dashboard\ITK\Modules\Filtering\GPUAnisotropicSmoothing\include\itkGPUAnisotropicDiffusionImageFilter.hxx(66,76):
 error C2187: syntax error: ')' was unexpected here
 [T:\Dashboard\ITK-build\Modules\Filtering\GPUAnisotropicSmoothing\ITKGPUAnisotropicSmoothingHeaderTest1.vcxproj]
```

raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=10232159